### ISSUE TITLE
implement the initial project setup

### ISSUE THREAD

**Issue by Okpainmo** [Okpainmo/team-x-deeco-project-clone_team-b#9]
This task is for team-leads only!!!

Implement the initial project setup - creating all necessary folders and files.

**Comment by Vctcode** [comment]
I will work on this ASAP

**Comment by Okpainmo** [comment]
You can proceed @Vctcode

**Comment by Vctcode** [comment]
Issue has been handled, reviewed and PR successful. Kindly close this issue.
